[package]
name = "Chainway"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.81"
hex = "0.4.3"
itertools = "0.12.1"
rs_merkle = "1.4.2"
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
sled = "0.34"
